site_name: aws-mini-book
site_url: https://github.com/augustoliks/aws-mini-book
site_description: AWS Concepts
site_author: Carlos Neto | @augustoliks
repo_name: augustoliks/aws-mini-book
repo_url: https://github.com/augustoliks/aws-mini-book
edit_uri: ''

nav:
  - Cloud Concepts: 01-concepts/cloud-concepts.md

theme:
  language: en
  name: material
  logo: aws-logo.svg
  favicon: aws-logo.svg
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Dark Mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Light Mode
  features:
    - search.suggest
    - search.highlight
    - navigation.top
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/augustoliks
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c-neto

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
